export const TECH_OPTIONS = [
  "React",
  "Vue.js",
  "Angular",
  "Next.js",
  "Node.js",
  "Express",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "TypeScript",
  "JavaScript",
  "Go",
  "Rust",
  "Java",
  "Kotlin",
  "Swift",
  "Flutter",
  "React Native",
  "PHP",
  "Laravel",
  "Ruby",
  "Rails",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "Supabase",
  "Docker",
  "Kubernetes",
  "AWS",
  "GCP",
  "Azure",
  "Tailwind CSS",
  "GraphQL",
  "REST API",
  "Git",
  "CI/CD",
  "Linux",
  "Machine Learning",
  "Data Science",
] as const;

export const ROLE_TYPE_LABELS: Record<string, string> = {
  frontend: "Frontend",
  backend: "Backend",
  fullstack: "Fullstack",
  data: "Data / IA",
  devops: "DevOps",
  mobile: "Mobile",
  autre: "Autre",
};

export const EXPERIENCE_LABELS: Record<string, string> = {
  junior: "Junior",
  mid: "Intermediaire",
  senior: "Senior",
};

export const PLACE_CATEGORIES = [
  "Restaurant",
  "Marché",
  "Café",
  "Pharmacie",
  "Hôpital",
  "École / Université",
  "Espace Tech",
  "Incubateur",
  "Autre",
] as const;
