import type { Project } from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    title: "Portefeuille Mobile Fintech",
    description:
      "Application de mobile money ciblant le secteur non bancarisé au Congo. Recherche d'un développeur Flutter Senior pour l'architecture front-end avec intégration MTN MoMo et Airtel Money.",
    tech_stack: ["Flutter", "Dart", "Firebase", "Mobile"],
    budget: "3 000$ – 5 000$ / mois",
    duration: "Long terme (1 an+)",
    collab_mode: "Hybride",
    open_to_collaboration: true,
    location: "Brazzaville",
    project_type: "Startup",
    priority: "Priorité Haute",
    author_id: "mock-author-1",
    author: {
      id: "mock-author-1",
      username: "lionel-ndoumou",
      full_name: "Lionel Ndoumou",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=LN&backgroundColor=0d9488",
    },
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-2",
    title: "Portail de Données E-Gov",
    description:
      "Plateforme sécurisée de partage de données municipales pour la mairie de Brazzaville. Besoin d'un ingénieur backend Python/Django avec expérience PostGIS pour la cartographie des équipements publics.",
    tech_stack: ["Python", "Django", "PostgreSQL", "PostGIS"],
    budget: "Contrat / TJM",
    duration: "6 – 12 mois",
    collab_mode: "Présentiel",
    open_to_collaboration: false,
    location: "Brazzaville • Secteur Public",
    project_type: "Public",
    priority: "Long Terme",
    author_id: "mock-author-2",
    author: {
      id: "mock-author-2",
      username: "service-numerique-bza",
      full_name: "Service Numérique BZA",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=SN&backgroundColor=1e40af",
    },
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-3",
    title: "Réseau Social Pro Congo",
    description:
      "LinkedIn congolais pour les professionnels de la tech et du business. Développement produit en TypeScript fullstack. Opportunité d'équity pour les fondateurs tech.",
    tech_stack: ["Next.js", "Supabase", "TypeScript", "Tailwind CSS"],
    budget: "Equity + Salaire",
    duration: "Long terme (1 an+)",
    collab_mode: "Remote",
    open_to_collaboration: true,
    location: "Remote",
    project_type: "Startup",
    priority: "Actif",
    author_id: "mock-author-3",
    author: {
      id: "mock-author-3",
      username: "grace-mabika",
      full_name: "Grace Mabika",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=GM&backgroundColor=7c3aed",
    },
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-4",
    title: "Plateforme Edtech Congo",
    description:
      "Cours en ligne en français pour les lycéens et étudiants congolais. Besoin d'un développeur mobile React Native et d'un designer UI/UX pour l'application Android/iOS.",
    tech_stack: ["React Native", "Node.js", "MongoDB", "AWS"],
    budget: "1 500$ – 3 000$ / mois",
    duration: "3 – 6 mois",
    collab_mode: "Remote",
    open_to_collaboration: true,
    location: "Pointe-Noire / Remote",
    project_type: "ONG",
    priority: "Actif",
    author_id: "mock-author-4",
    author: {
      id: "mock-author-4",
      username: "boris-kimfoueti",
      full_name: "Boris Kimfoueti",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=BK&backgroundColor=b45309",
    },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-5",
    title: "Logistique & Tracking Colis",
    description:
      "Solution de suivi de colis en temps réel pour les livreurs de Brazzaville et Pointe-Noire. Stack React + Node.js + WebSocket. Mission freelance avec possibilité d'intégration.",
    tech_stack: ["React", "Node.js", "WebSocket", "PostgreSQL"],
    budget: "500$ – 1 500$ / mois",
    duration: "1 – 3 mois",
    collab_mode: "Hybride",
    open_to_collaboration: true,
    location: "Brazzaville",
    project_type: "Startup",
    priority: "Urgent",
    author_id: "mock-author-5",
    author: {
      id: "mock-author-5",
      username: "prince-ossombo",
      full_name: "Prince Ossombo",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=PO&backgroundColor=be123c",
    },
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-6",
    title: "Cybersécurité PME Congolaises",
    description:
      "Audit et mise en conformité des systèmes informatiques de PME locales. Recherche d'un expert cybersécurité + sysadmin pour des missions ponctuelles et formations.",
    tech_stack: ["Linux", "Cybersécurité", "Réseaux", "Python"],
    budget: "Contrat / TJM",
    duration: "Indéterminé",
    collab_mode: "Présentiel",
    open_to_collaboration: true,
    location: "Brazzaville / Pointe-Noire",
    project_type: "Personnel",
    priority: "Ouvert",
    author_id: "mock-author-6",
    author: {
      id: "mock-author-6",
      username: "arnaud-loubaki",
      full_name: "Arnaud Loubaki",
      avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=AL&backgroundColor=065f46",
    },
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
