import type { Profile } from "@/types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "mock-1",
    username: "jb-moukoko",
    full_name: "Jean-Baptiste Moukoko",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=JBM&backgroundColor=0d9488",
    bio: "Passionné de web, je construis des interfaces modernes et performantes.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/jb-moukoko",
    tech_stack: ["React", "TypeScript", "Tailwind CSS", "Node.js"],
    role_type: "frontend",
    experience_level: "senior",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-01-10T08:00:00Z",
    updated_at: "2026-05-20T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "mock-2",
    username: "grace-ngoma",
    full_name: "Grace Ngoma",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=GN&backgroundColor=7c3aed",
    bio: "Architecte backend spécialisée en APIs REST et systèmes distribués.",
    city: "Pointe-Noire",
    latitude: -4.7692,
    longitude: 11.8660,
    github_url: "https://github.com/grace-ngoma",
    tech_stack: ["Python", "Django", "PostgreSQL", "Docker", "Redis"],
    role_type: "backend",
    experience_level: "senior",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-05-18T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "mock-3",
    username: "patrick-loemba",
    full_name: "Patrick Loemba",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=PL&backgroundColor=0891b2",
    bio: "Développeur fullstack, j'aime construire des produits de A à Z.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/patrick-loemba",
    tech_stack: ["Vue.js", "Laravel", "MySQL", "Docker"],
    role_type: "fullstack",
    experience_level: "mid",
    open_to_collaboration: false,
    role: "contributor",
    created_at: "2026-02-01T08:00:00Z",
    updated_at: "2026-05-15T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "mock-4",
    username: "aurelia-nkounkou",
    full_name: "Aurélia Nkounkou",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=AN&backgroundColor=be185d",
    bio: "Data scientist, j'explore les données pour en extraire de la valeur.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/aurelia-nkounkou",
    tech_stack: ["Python", "TensorFlow", "Pandas", "SQL", "Power BI"],
    role_type: "data",
    experience_level: "mid",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-02-10T08:00:00Z",
    updated_at: "2026-05-22T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "mock-5",
    username: "chris-mabiala",
    full_name: "Chris Mabiala",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=CM&backgroundColor=d97706",
    bio: "Dev mobile, je crée des apps Android et iOS avec Flutter.",
    city: "Dolisie",
    latitude: -4.1994,
    longitude: 12.6731,
    github_url: "https://github.com/chris-mabiala",
    tech_stack: ["Flutter", "Dart", "Firebase", "Kotlin"],
    role_type: "mobile",
    experience_level: "junior",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-05-10T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "mock-6",
    username: "sandra-bouanga",
    full_name: "Sandra Bouanga",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=SB&backgroundColor=059669",
    bio: "Ingénieure DevOps, j'automatise les déploiements et sécurise les infrastructures.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/sandra-bouanga",
    tech_stack: ["Docker", "Kubernetes", "Terraform", "AWS", "GitHub Actions"],
    role_type: "devops",
    experience_level: "senior",
    open_to_collaboration: false,
    role: "contributor",
    created_at: "2026-01-20T08:00:00Z",
    updated_at: "2026-05-21T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "mock-7",
    username: "david-nganga",
    full_name: "David Nganga",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=DN&backgroundColor=1d4ed8",
    bio: "Frontend developer, je transforme les maquettes en expériences web fluides.",
    city: "Pointe-Noire",
    latitude: -4.7692,
    longitude: 11.8660,
    github_url: "https://github.com/david-nganga",
    tech_stack: ["React", "Next.js", "TypeScript", "Figma"],
    role_type: "frontend",
    experience_level: "mid",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-02-20T08:00:00Z",
    updated_at: "2026-05-19T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "mock-8",
    username: "flore-mouamba",
    full_name: "Flore Mouamba",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=FM&backgroundColor=9333ea",
    bio: "Fullstack JS, j'aime les projets à impact social.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/flore-mouamba",
    tech_stack: ["Node.js", "Express", "React", "MongoDB"],
    role_type: "fullstack",
    experience_level: "junior",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-03-15T08:00:00Z",
    updated_at: "2026-05-23T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: "mock-9",
    username: "kevin-itoua",
    full_name: "Kévin Itoua",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=KI&backgroundColor=0f766e",
    bio: "Développeur backend Java, j'adore les architectures microservices.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "https://github.com/kevin-itoua",
    tech_stack: ["Java", "Spring Boot", "PostgreSQL", "Kafka"],
    role_type: "backend",
    experience_level: "mid",
    open_to_collaboration: false,
    role: "contributor",
    created_at: "2026-02-05T08:00:00Z",
    updated_at: "2026-05-17T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "mock-10",
    username: "marie-bazolo",
    full_name: "Marie-Claire Bazolo",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=MB&backgroundColor=dc2626",
    bio: "Développeuse mobile React Native, je crée des apps cross-platform.",
    city: "Pointe-Noire",
    latitude: -4.7692,
    longitude: 11.8660,
    github_url: "https://github.com/marie-bazolo",
    tech_stack: ["React Native", "TypeScript", "Firebase", "Expo"],
    role_type: "mobile",
    experience_level: "mid",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-03-10T08:00:00Z",
    updated_at: "2026-05-22T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "mock-11",
    username: "arsene-mialoundama",
    full_name: "Arsène Mialoundama",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=AM&backgroundColor=854d0e",
    bio: "Ingénieur data, je construis des pipelines ETL et des dashboards analytiques.",
    city: "Brazzaville",
    latitude: -4.2634,
    longitude: 15.2429,
    github_url: "",
    tech_stack: ["Python", "Spark", "dbt", "Airflow", "BigQuery"],
    role_type: "data",
    experience_level: "senior",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-01-25T08:00:00Z",
    updated_at: "2026-05-20T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "mock-12",
    username: "joelle-ngouma",
    full_name: "Joëlle Ngouma",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=JN&backgroundColor=0369a1",
    bio: "Développeuse fullstack PHP/React, j'aime les challenges techniques.",
    city: "Dolisie",
    latitude: -4.1994,
    longitude: 12.6731,
    github_url: "https://github.com/joelle-ngouma",
    tech_stack: ["PHP", "Laravel", "React", "MySQL", "Redis"],
    role_type: "fullstack",
    experience_level: "mid",
    open_to_collaboration: true,
    role: "contributor",
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-05-24T10:00:00Z",
    last_seen_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];
