name: Auto Merge Dependabot

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: